import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <nav className="w-full bg-white border-b">
        <div className="max-w-4xl mx-auto px-4 py-3 flex gap-4">
          <Link href="/" className="hover:underline">สุ่มเมนู</Link>
          <Link href="/add_menu" className="hover:underline">เพิ่มเมนู</Link>
          <Link href="/list_menu" className="hover:underline">ดูรายการทั้งหมด</Link>
        </div>
      </nav>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body> */}


      <body className="min-h-screen bg-gray-50">
        <nav className="w-full bg-white border-b">
          <div className="max-w-4xl mx-auto px-4 py-3 flex gap-4">
            <Link href="/" className="hover:underline">สุ่มเมนู</Link>
            <Link href="/add_menu" className="hover:underline">เพิ่มเมนู</Link>
            <Link href="/list_menu" className="hover:underline">ดูรายการทั้งหมด</Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
